# Generated by Django 5.0.4 on 2024-11-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_school_name_school_name_school_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstNAme',
            new_name='firstName',
        ),
    ]
