# Generated by Django 5.0.4 on 2024-11-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_firstname_student_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app.student'),
        ),
    ]
