# Generated by Django 5.1.4 on 2024-12-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_school_cachet_school_contact_school_devise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='card_file',
            field=models.FileField(blank=True, help_text='Fichier PDF de la carte générée.', null=True, upload_to='card/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image_url',
            field=models.CharField(blank=True, help_text="Lien vers l'image de l'étudiant.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=10, null=True),
        ),
    ]
