# Generated by Django 5.0.4 on 2024-11-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cart_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='contact',
            new_name='phone',
        ),
    ]
