# Generated by Django 5.1.4 on 2024-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_card_file_alter_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprototype',
            name='school_choice',
            field=models.ManyToManyField(blank=True, null=True, related_name='prototype', to='app.school'),
        ),
    ]
