# Generated by Django 5.0.4 on 2024-12-17 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cart_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='academic_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='cachet',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='photos',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.BinaryField(null=True),
        ),
    ]
