# Generated by Django 5.0.4 on 2024-12-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_school_academic_year_school_cachet_school_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='signature_principake',
            field=models.BinaryField(null=True),
        ),
    ]
