# Generated by Django 5.1.4 on 2024-12-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cardprototype_school_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classe',
            new_name='classe_id',
        ),
        migrations.AlterField(
            model_name='cardprototype',
            name='school_choice',
            field=models.ManyToManyField(blank=True, related_name='prototype', to='app.school'),
        ),
    ]
