# Generated by Django 5.0.4 on 2024-11-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_contact_school_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_file',
            field=models.FileField(default='', upload_to='media/cart/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/schools/signature/'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='media/students/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='sexe',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='app.student'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(upload_to='media/schools/'),
        ),
    ]
