# Generated by Django 5.0.4 on 2024-12-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_school_signature_principake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='cachet',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='signature_principake',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photos',
            field=models.TextField(null=True),
        ),
    ]
