# Generated by Django 5.0.4 on 2024-11-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_firstname_student_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
