# Generated by Django 5.0.4 on 2024-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_first_name_student_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_file',
            field=models.FileField(upload_to='cartd'),
        ),
    ]
