# Generated by Django 5.0.4 on 2024-12-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cart_image_alter_school_cachet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='signature_principake',
            new_name='signature_principale',
        ),
    ]
