# Generated by Django 5.0.4 on 2024-12-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cart_cart_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=256)),
                ('choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='school',
            name='signature',
        ),
        migrations.AddField(
            model_name='school',
            name='academic_year',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_file',
            field=models.FileField(upload_to='card/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='students/'),
        ),
    ]
